name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: regex
          # Update after we will switch to CalVer version for coffea
          #regex_pattern: 'release: \"\d{4}\.\d{1,2}\.\d+\"'
          regex_pattern: 'release: \"\d+\.\d+\.\d+\"'
          root: ".github/workflows/gh-ci.yml"
