# Only test building images
name: PullRequest

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_ORG: coffeateam
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:

  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE_DIR: [base, base-cc7]
    name: ${{ matrix.IMAGE_DIR }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Image
      run: |
        IMAGE=coffea-${{ matrix.IMAGE_DIR }}
        echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

        cd ${{ matrix.IMAGE_DIR }}
        docker build -t ${DOCKER_ORG}/${IMAGE}:PR .

    - name: Make sure voms tools are working
      run: |
        ERROR=$(docker run ${DOCKER_ORG}/${IMAGE}:PR voms-proxy-info 2>&1 > /dev/null; exit 0)
        TEST=$(echo -e "\nCouldn't find a valid proxy.\n")

        if [ "$ERROR" == "$TEST" ]; then
          exit 0
        else
          exit 1
        fi

    - name: Export Full Conda Environment
      run: |
        docker run ${DOCKER_ORG}/${IMAGE}:PR conda list --export
